### ISSUE TITLE
Use snake case for release stage

### ISSUE THREAD

**Issue by fbjork** [jarednorman/bugsnag-elixir#12]
I noticed releaseStage isn't snake cased here:
https://github.com/jarednorman/bugsnag-elixir/blob/master/lib/bugsnag/payload.ex#L25

Not a bug, but should be updated according to Elixir conventions.

**Comment by jarednorman** [comment]
Yep. Pull requests accepted!

**Comment by fbjork** [comment]
@jarednorman here you go! https://github.com/jarednorman/bugsnag-elixir/pull/13
