### ISSUE TITLE
Release New Version to Hex

### ISSUE THREAD

**Issue by dcuddeback** [jarednorman/bugsnag-elixir#18]
I'd love to be able to use different release stages with Bugsnag, which was added to the library last June (in 9a3e15d973ca04bd49b1036f4622415351abd43e). Would you consider releasing a new version to Hex?

**Comment by fbjork** [comment]
@jarednorman ping! Friendly reminder to release new version to Hex:)

**Comment by jarednorman** [comment]
Ahh, I forgot. I will make an effort to cut a release this weekend but am travelling so no guarantees.
