### ISSUE TITLE
How to use the Bugsnag.Logger?

### ISSUE THREAD

**Issue by vorce** [jarednorman/bugsnag-elixir#27]
I'm trying to send unexpected errors (such as when a process dies) to bugsnag. Is that possible with `Bugsnag.Logger`? If not how would I go about it?

I've set bugsnag up like this in my config:

    config :bugsnag, api_key: System.get_env("BUGSNAG_API_KEY")
    config :bugsnag, release_stage: "#{Mix.env}"
    config :bugsnag, use_logger: true

Is that the right way to enable `Bugsnag.Logger`? Also how can I simulate/trigger an error that `Bugsnag.Logger` will send? I've tried sending an unknown message to a process, but the resulting error does not match the pattern for `handle_event({:error_report, _gl, {_pid, _type, [message | _]}}, state) when is_list(message)`.

**Comment by mootpointer** [comment]
That logger is a handler for Erlang's [Error Logger](
http://erlang.org/doc/man/error_logger.html).

We're currently working on a way of sending errors which are not exceptions
to Bugsnag, but it isn't presently supported.

**Comment by vorce** [comment]
Thanks @mootpointer, that much I've understood. I just can't seem to actually make it send anything to bugsnag. I've also tried copying some of the stuff from the tests to no avail.

**Comment by mootpointer** [comment]
Tells me we should probably work on docs then...

`Bugsnag.report(exception)` is the standard way of reporting an exception.

**Comment by vorce** [comment]
Reporting individual exceptions with `Bugsnag.report(exception)` works like a charm. ❤️

My problem is that I'd like to use the included logger backend to send off things that I do not `rescue` (and thus cannot use Bugsnag.report for). But that I can't get to work for some reason, I'm suspecting that I'm not triggering the right types of errors (that would pass the pattern match) inside the Bugsnag.Logger. Am I making sense? :)
