### ISSUE TITLE
Add a `notify_release_stages` option

### ISSUE THREAD

**Issue by DamirSvrtan** [jarednorman/bugsnag-elixir#32]
Hey @jarednorman,

Thnx for building this package!
The official Ruby package has an option called `notify_release_stages` which states in what rack environments it is going to report errors.

Is there such an option in this package? If not, I'd be willing to do it through a pull request, just wondering if you're interested in merging it in.

Thnx.

**Comment by jarednorman** [comment]
That sounds reasonable. @mootpointer is maintaining this currently though.

**Comment by ashwini709** [comment]
@mootpointer This was fixed by #43  and can be closed.

**Comment by mootpointer** [comment]
Thanks.
