### ISSUE TITLE
`use_logger` is Compulsory

### ISSUE THREAD

**Issue by IceDragon200** [jarednorman/bugsnag-elixir#39]
tl;dr
**Expected:**
```elixir
# stop bugsnag from collecting test errors (it's always running locally so we can see the errors anyway)
config :bugsnag, use_logger: false
```

**Actual**
```
** (Mix) Could not start application bugsnag: exited in: Bugsnag.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: "false"
            (bugsnag) lib/bugsnag.ex:15: Bugsnag.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

So, it doesn't matter if you set it to false, it **MUST** be true, the process will fail to start otherwise:

https://github.com/jarednorman/bugsnag-elixir/blob/master/lib/bugsnag.ex#L15-L17

My only question, was this intended? 
If yes, why bother giving the option in the first place if it's mandatory? Why not give it an actual human-readable error message?
else, can we change it to ignore <everything else>?

**Comment by mootpointer** [comment]
You're right. That looks like a bug.

I had other questions about that line which blinded me to the more obvious issue. I'll commit a fix in a moment.
