### ISSUE TITLE
use GenEvent is deprecated

### ISSUE THREAD

**Issue by PavelTyk** [jarednorman/bugsnag-elixir#59]
```
==> bugsnag
Compiling 3 files (.ex)
warning: use GenEvent is deprecated, use one of the alternatives described in the documentation for the GenEvent module
  lib/bugsnag/logger.ex:5

warning: the GenEvent module is deprecated, see its documentation for alternatives
  lib/bugsnag/logger.ex:5
```

**Comment by PavelTyk** [comment]
@jarednorman are you accepting pull requests? I can setup a fix for that.

**Comment by jarednorman** [comment]
We are accepting pull requests! There a couple of new maintainers who will handle them instead of me though. 😄

**Comment by shantiii** [comment]
@grantovich probably we can close this ticket with the merge of #69

**Comment by grantovich** [comment]
Ah, of course! Further discussion should probably happen in #67.
