### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Ciboulette** [jarednorman/bugsnag-elixir#75]
Hello Bugsnag user, 

I've tried all the possibility, I can't manage to make bugsnag-elixir work to report all uncaught exceptions. 

I've tried on a simple elixir app and simple phoenix app, it didn't work as expected. I can manually report exception but not uncaught ones. 

I'm using Elixir 1.5.3, Erlang OTP 20 [erts-9.2.1].

I've created a [test example repository](https://github.com/Ciboulette/test_bugsnag_elixir
) to help you see what is not working properly.. 

Feel free to help 🙏 Thanks

**Comment by shonfeder** [comment]
@Ciboulette it looks like you worked this out! Kudos. However, I'm also not seeing uncaught exceptions raised. Any insight you can share about what you did to get it working?

**Comment by Ciboulette** [comment]
Oh @shonfeder sorry to hear this but I've managed to make it works by using https://github.com/getsentry/sentry-elixir, Sorry Bugsnag 😅

**Comment by shonfeder** [comment]
Thanks, @Ciboulette! We ended up using https://github.com/jarednorman/plugsnag, which seems to be helping catch most stuff. Always good to know of more tools to keep in the box though!
