### ISSUE TITLE
UndefinedFunctionError not being captured?

### ISSUE THREAD

**Issue by stephanos** [jarednorman/bugsnag-elixir#87]
Hello!

We recently noticed that most errors are successfully captured and sent to Bugsnag, however, `UndefinedFunctionError` doesn't seem to be one of them. I can trigger an `ArithmeticError`, for example, and see it makes its way to Bugsnag. But when I call a function with more/less arguments, it doesn't get to Bugsnag.

I tried adding logs everywhere but came up empty handed.

Is there an explanation for this?

**Comment by stephanos** [comment]
Okay, I'm not sure why one works and the other one doesn't. Both payloads look fine, and I get a 200 OK from Bugsnag. I've reached out to Bugsnag support to ask what's up.

**Comment by stephanos** [comment]
Okay, I figured it out 🤦‍♂ 

So the payload for an `UndefinedFunctionError` has one significant difference from other payloads, the top frame that is sent to Bugsnag looks like this:

```
{
  "method": "<the function that does not exist>",
  "lineNumber": 0,
  "inProject": false,
  "file": "unknown"
},
```

This is important since Bugsnag, by default anyway, groups like this:

> Grouped with other events sharing the same error class, file and line number of the top in-project stackframe of the innermost exception.

This means that all `UndefinedFunctionError` are grouped into the same error. Which IMHO is definitely not desirable. In our case we _ignored_ an occurrence of this and then never saw another error of this type again because of the grouping.

So, my proposal is to _drop_ the top frame here. The name of the function is part of the message already. So we wouldn't lose anything. The top frame I printed above doesn't contain any useful information. So I think that would be the best course of action here. I can prepare a PR.

What do you think, @jarednorman?

**Comment by jarednorman** [comment]
That seems like a reasonable solution.

**Comment by stephanos** [comment]
PR: https://github.com/jarednorman/bugsnag-elixir/pull/88
